main: dev.mejmenCorps.extendedSurvival.extendedSurvival
name: ExtendedSurvival
author: MejmenCorps
version: 0.1
description: This is the best plugin you ever seen! Btw you got really neat stuff now in your survival!